global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: '/prome'
    scheme: 'http'
    static_configs:
      - targets: ['153.92.5.249:9000']