node {
    // Mendefinisikan variabel untuk menyimpan hasil test
    def testResults
    
    stage('Build') {
        // Menggunakan docker.image().inside() untuk menjalankan container Python
        docker.image('python:2-alpine').inside {
            // Kompilasi file Python
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    
    stage('Test') {
        // Menjalankan pengujian menggunakan pytest dalam container
        docker.image('qnib/pytest').inside {
            // Menjalankan pytest dan menyimpan hasil dalam file XML
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            
            // Mengumpulkan hasil test menggunakan junit
            junit 'test-reports/results.xml'
        }
    }
    
    stage('Deliver') {
        // Membuat executable menggunakan PyInstaller
        docker.image('cdrx/pyinstaller-linux:python2').inside {
            // Membuat executable file
            sh 'pyinstaller --onefile sources/add2vals.py'
            
            // Mengarsipkan hasil build jika berhasil
            archiveArtifacts 'dist/add2vals'
        }
    }
}